development:
  adapter: postgresql
  encoding: unicode
  database: blueapron_store_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: blueapron_store_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: blueapron_store
  pool: 5
  password: 
