# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa080c5089f758c6acc524b2f2edb313be7d048e3cac18976fc3f3787ca6c058640f41060d3f377e3533e782927ce9e778bfd9ca7a057539acca1912efd83533

test:
  secret_key_base: 2233838cf99eb2d48cfcb1b4f4820e8c2c6da8505d107266ebbddce1e686d3e92d46255f54c039d2589bdaba9a5ed69183ea2b2cf98486f0858f840007c6473a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
